name: .NET Core

on: [push]

jobs:
  build:
    name: publish to nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 
    - name: Publish NuGet
      uses: rohith/publish-nuget@v1.0.3
      with:
        nuget_key: "oy2jz2ls4vmy5sob3gyqv27spaslvibuzlpwitzvyzptzq"
